// <auto-generated />
using FlipMemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlipMemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251022125517_DictionaryRelationship")]
    partial class DictionaryRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // -----------------------------
            // DictionaryWord join table
            // -----------------------------
            modelBuilder.Entity("DictionaryWord", b =>
                {
                    b.Property<int>("DictionariesId")
                        .HasColumnType("integer");

                    b.Property<int>("WordsId")
                        .HasColumnType("integer");

                    b.HasKey("DictionariesId", "WordsId");

                    b.HasIndex("WordsId");

                    b.ToTable("DictionaryWord");
                });

            // -----------------------------
            // Foreign key constraints
            // -----------------------------
            modelBuilder.Entity("DictionaryWord", b =>
                {
                    b.HasOne("FlipMemo.Models.Dictionary", null)
                        .WithMany()
                        .HasForeignKey("DictionariesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlipMemo.Models.Answer", null)
                        .WithMany()
                        .HasForeignKey("WordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
