namespace FlipMemo.Utils;

public static class LanguageCodes
{
    public const string Albanian = "sq";
    public const string Arabic = "ar";
    public const string Belarusian = "be";
    public const string Bengali = "bn";
    public const string Bosnian = "bs";
    public const string Bulgarian = "bg";
    public const string ChineseSimplified = "zh-Hans";
    public const string ChineseTraditional = "zh-Hant";
    public const string Croatian = "hr";
    public const string Czech = "cs";
    public const string Danish = "da";
    public const string Dutch = "nl";
    public const string English = "en";
    public const string Estonian = "et";
    public const string Finnish = "fi";
    public const string French = "fr";
    public const string German = "de";
    public const string Greek = "el";
    public const string Hebrew = "he";
    public const string Hindi = "hi";
    public const string Hungarian = "hu";
    public const string Icelandic = "is";
    public const string Indonesian = "id";
    public const string Italian = "it";
    public const string Japanese = "ja";
    public const string Korean = "ko";
    public const string Latvian = "lv";
    public const string Lithuanian = "lt";
    public const string Macedonian = "mk";
    public const string Malay = "ms";
    public const string Montenegrin = "cnr";
    public const string Norwegian = "no";
    public const string Persian = "fa";
    public const string Polish = "pl";
    public const string Portuguese = "pt";
    public const string Romanian = "ro";
    public const string Russian = "ru";
    public const string Serbian = "sr";
    public const string Slovak = "sk";
    public const string Slovenian = "sl";
    public const string Spanish = "es";
    public const string Swedish = "sv";
    public const string Thai = "th";
    public const string Turkish = "tr";
    public const string Ukrainian = "uk";
    public const string Urdu = "ur";
    public const string Vietnamese = "vi";
}
