export { default as Home } from "./Home.tsx";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Logout } from "./Logout";
export { default as Missing } from "./Missing";
export { default as Welcome } from "./Welcome.tsx";
export { default as ForgotPassword } from "./ForgotPassword.tsx";
export { default as ChangePassword } from "./ChangePassword.tsx";
export { default as ChooseStyle } from "./ChooseStyle.tsx";
export { default as ChooseWordSet } from "./ChooseWordSet.tsx";
export {default as UserControl} from "./UserControl.tsx";
export { default as AdminPage} from "./AdminPage.tsx";
export { default as AdminDictionary} from "./AdminDictionary.tsx";
export { default as AdminAddDictionary} from "./AdminAddDictionary.tsx";
export { default as AdminAddWord} from "./AdminAddWord.tsx";
export { default as GameTemplate} from "./GameTemplate.tsx";
